import java.util.*;

class Solution {
    public int[] shortestAlternatingPaths(int n, int[][] redEdges, int[][] blueEdges) {
            ArrayList<ArrayList<Integer>> red = new ArrayList<>();
                    ArrayList<ArrayList<Integer>> blue = new ArrayList<>();

                            for (int i = 0; i < n; i++) {
                                        red.add(new ArrayList<>());
                                                    blue.add(new ArrayList<>());
                                                            }

                                                                    for (int[] edge : redEdges) {
                                                                                red.get(edge[0]).add(edge[1]);
                                                                                        }

                                                                                                for (int[] edge : blueEdges) {
                                                                                                            blue.get(edge[0]).add(edge[1]);
                                                                                                                    }

                                                                                                                            int[] answer = new int[n];
                                                                                                                                    Arrays.fill(answer, -1);

                                                                                                                                            boolean[][] visited = new boolean[n][2];

                                                                                                                                                    Queue<int[]> queue = new LinkedList<>();

                                                                                                                                                            // color 0 = red, color 1 = blue
                                                                                                                                                                    queue.add(new int[]{0, 0, 0});
                                                                                                                                                                            queue.add(new int[]{0, 1, 0});

                                                                                                                                                                                    visited[0][0] = true;
                                                                                                                                                                                            visited[0][1] = true;

                                                                                                                                                                                                    while (!queue.isEmpty()) {
                                                                                                                                                                                                                int[] current = queue.poll();

                                                                                                                                                                                                                            int node = current[0];
                                                                                                                                                                                                                                        int color = current[1];
                                                                                                                                                                                                                                                    int distance = current[2];

                                                                                                                                                                                                                                                                if (answer[node] == -1) {
                                                                                                                                                                                                                                                                                answer[node] = distance;
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                        if (color == 0) {
                                                                                                                                                                                                                                                                                                                        for (int next : blue.get(node)) {
                                                                                                                                                                                                                                                                                                                                            if (!visited[next][1]) {
                                                                                                                                                                                                                                                                                                                                                                    visited[next][1] = true;
                                                                                                                                                                                                                                                                                                                                                                                            queue.add(new int[]{next, 1, distance + 1});
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int next : red.get(node)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!visited[next][0]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        visited[next][0] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                queue.add(new int[]{next, 0, distance + 1});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return answer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }