import java.util.*;

class Solution {
    public int[] sortItems(int n, int m, int[] group, List<List<Integer>> beforeItems) {
            
                    // Give unique group id to items with group -1
                            for (int i = 0; i < n; i++) {
                                        if (group[i] == -1) {
                                                        group[i] = m;
                                                                        m++;
                                                                                    }
                                                                                            }

                                                                                                    List<List<Integer>> itemGraph = new ArrayList<>();
                                                                                                            List<List<Integer>> groupGraph = new ArrayList<>();

                                                                                                                    for (int i = 0; i < n; i++) {
                                                                                                                                itemGraph.add(new ArrayList<>());
                                                                                                                                        }

                                                                                                                                                for (int i = 0; i < m; i++) {
                                                                                                                                                            groupGraph.add(new ArrayList<>());
                                                                                                                                                                    }

                                                                                                                                                                            int[] itemIndegree = new int[n];
                                                                                                                                                                                    int[] groupIndegree = new int[m];

                                                                                                                                                                                            for (int curr = 0; curr < n; curr++) {
                                                                                                                                                                                                        for (int prev : beforeItems.get(curr)) {
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        // item dependency
                                                                                                                                                                                                                                                        itemGraph.get(prev).add(curr);
                                                                                                                                                                                                                                                                        itemIndegree[curr]++;

                                                                                                                                                                                                                                                                                        // group dependency
                                                                                                                                                                                                                                                                                                        if (group[prev] != group[curr]) {
                                                                                                                                                                                                                                                                                                                            groupGraph.get(group[prev]).add(group[curr]);
                                                                                                                                                                                                                                                                                                                                                groupIndegree[group[curr]]++;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                            List<Integer> itemOrder = topoSort(itemGraph, itemIndegree);
                                                                                                                                                                                                                                                                                                                                                                                                    List<Integer> groupOrder = topoSort(groupGraph, groupIndegree);

                                                                                                                                                                                                                                                                                                                                                                                                            if (itemOrder.size() != n || groupOrder.size() != m) {
                                                                                                                                                                                                                                                                                                                                                                                                                        return new int[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                        Map<Integer, List<Integer>> groupToItems = new HashMap<>();

                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int item : itemOrder) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            int g = group[item];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        groupToItems.putIfAbsent(g, new ArrayList<>());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    groupToItems.get(g).add(item);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int[] result = new int[n];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int index = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int g : groupOrder) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (groupToItems.containsKey(g)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int item : groupToItems.get(g)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result[index++] = item;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private List<Integer> topoSort(List<List<Integer>> graph, int[] indegree) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Queue<Integer> queue = new LinkedList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        List<Integer> order = new ArrayList<>();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < indegree.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (indegree[i] == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            queue.add(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while (!queue.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int curr = queue.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                order.add(curr);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int next : graph.get(curr)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            indegree[next]--;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (indegree[next] == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                queue.add(next);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return order;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }