import java.util.*;

class Solution {
    public List<List<String>> accountsMerge(List<List<String>> accounts) {
            int n = accounts.size();

                    DSU dsu = new DSU(n);

                            HashMap<String, Integer> emailToIndex = new HashMap<>();

                                    // Union accounts with same email
                                            for (int i = 0; i < n; i++) {
                                                        List<String> account = accounts.get(i);

                                                                    for (int j = 1; j < account.size(); j++) {
                                                                                    String email = account.get(j);

                                                                                                    if (!emailToIndex.containsKey(email)) {
                                                                                                                        emailToIndex.put(email, i);
                                                                                                                                        } else {
                                                                                                                                                            dsu.union(i, emailToIndex.get(email));
                                                                                                                                                                            }
                                                                                                                                                                                        }
                                                                                                                                                                                                }

                                                                                                                                                                                                        // Store emails by parent account
                                                                                                                                                                                                                HashMap<Integer, TreeSet<String>> map = new HashMap<>();

                                                                                                                                                                                                                        for (String email : emailToIndex.keySet()) {
                                                                                                                                                                                                                                    int parent = dsu.find(emailToIndex.get(email));

                                                                                                                                                                                                                                                map.putIfAbsent(parent, new TreeSet<>());
                                                                                                                                                                                                                                                            map.get(parent).add(email);
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                            List<List<String>> result = new ArrayList<>();

                                                                                                                                                                                                                                                                                    for (int parent : map.keySet()) {
                                                                                                                                                                                                                                                                                                List<String> merged = new ArrayList<>();

                                                                                                                                                                                                                                                                                                            merged.add(accounts.get(parent).get(0));
                                                                                                                                                                                                                                                                                                                        merged.addAll(map.get(parent));

                                                                                                                                                                                                                                                                                                                                    result.add(merged);
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                    return result;
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                        class DSU {
                                                                                                                                                                                                                                                                                                                                                            int[] parent;

                                                                                                                                                                                                                                                                                                                                                                DSU(int n) {
                                                                                                                                                                                                                                                                                                                                                                        parent = new int[n];

                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                            parent[i] = i;
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                            int find(int x) {
                                                                                                                                                                                                                                                                                                                                                                                                                    if (parent[x] != x) {
                                                                                                                                                                                                                                                                                                                                                                                                                                parent[x] = find(parent[x]);
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                return parent[x];
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        void union(int a, int b) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                int parentA = find(a);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int parentB = find(b);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (parentA != parentB) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            parent[parentB] = parentA;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }